### ISSUE TITLE
2019.3 "not supported"

### ISSUE THREAD

**Issue by MeikelLP** [peeweek/net.peeweek.gameplay-ingredients#13]
[The docs say](https://peeweek.readthedocs.io/en/latest/gameplay-ingredients/) that 2019.3 is not supported.

However 2019.3.x is available [on openupm](https://openupm.com/packages/net.peeweek.gameplay-ingredients/).
The [README.md](https://github.com/peeweek/net.peeweek.gameplay-ingredients/blob/master/README.md) also states this.

Please update the docs to avoid confusion :)

**Comment by peeweek** [comment]
You are absolutely right! Thanks for pointing that out :)

**Comment by peeweek** [comment]
Latest docs should resolve this :)
