### ISSUE TITLE
Timeline version requirement missing from documentation

### ISSUE THREAD

**Issue by shanepadgett** [peeweek/net.peeweek.gameplay-ingredients#19]
Unity Version: 2019.3.14f1

Installed using `openupm add net.peeweek.gameplay-ingredients`

Get the error in the image. You need to first manually update timeline to the required version before you can open a project with this package. I believe this should be noted in the documentation.

![image](https://user-images.githubusercontent.com/29068876/83215710-37ccf280-a12d-11ea-9015-5f0fce903de0.png)

**Comment by peeweek** [comment]
You're right, I have added a package dependency history to the documentation : https://peeweek.readthedocs.io/en/latest/gameplay-ingredients/#package-dependency-history
