### ISSUE TITLE
in 2018.lts shortcuts get canibalized by GI

### ISSUE THREAD

**Issue by laurentopia** [peeweek/net.peeweek.gameplay-ingredients#20]
For example I select one of the state then create a script, the welcome screen appears again for some reason, then I try to rename the script but rename don't work - slide mouse and f2
ctrl+d also doesn't work when the editor is stuck in this mode

**Comment by peeweek** [comment]
I have slightly changed the behavior of the "Show on Startup" so it doesn't open on domain reload (after script changes). Using 2019.3.7 and 2020.2.0, it should display only on startup. Could you confirm that this new behavior doesn't bother while renaming again?
