### ISSUE TITLE
Disabling Virtual Camera Manager in the Settings asset results in errors every frame

### ISSUE THREAD

**Issue by laurenth-unity** [peeweek/net.peeweek.gameplay-ingredients#5]
Manager of type 'GameplayIngredients.VirtualCameraManager' could not be accessed. Check the excludedManagers list in your GameplayIngredientsSettings configuration file.
UnityEngine.Debug:LogError(Object)
GameplayIngredients.Manager:Get() (at LocalPackages/net.peeweek.gameplay-ingredients/Runtime/Managers/Manager.cs:19)
GameplayIngredients.Editor.LinkGameView:Update(SceneView) (at LocalPackages/net.peeweek.gameplay-ingredients/Editor/GameViewLink/LinkGameView.cs:121)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by peeweek** [comment]
Forgot to solve the issue, was done in the commit: 

b63bc5f - Fixed LinkGameView not working in play mode when excluding VirtualCameraManager
