### ISSUE TITLE
ArgumentOutOfRangeException: Index was out of range.  @5b823b4dbb/Editor/GameViewLink/LinkGameView.cs:247

### ISSUE THREAD

**Issue by twobob** [peeweek/net.peeweek.gameplay-ingredients#60]
`ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Collections.Generic.List"1[T].get_Item (System.Int32 index) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cinemachine.CinemachineBrain.UpdateFrame0 (System.Single deltaTime) (at Library/PackageCache/com.unity.cinemachine@2.6.5/Runtime/Behaviours/CinemachineBrain.cs:618)
Cinemachine.CinemachineBrain.ManualUpdate () (at Library/PackageCache/com.unity.cinemachine@2.6.5/Runtime/Behaviours/CinemachineBrain.cs:336)
GameplayIngredients.Editor.LinkGameView.UpdateCinemachinePreview (System.Boolean value) (at Library/PackageCache/net.peeweek.gameplay-ingredients@5b823b4dbb/Editor/GameViewLink/LinkGameView.cs:247)
GameplayIngredients.Editor.LinkGameView.set_CinemachineActive (System.Boolean value) (at Library/PackageCache/net.peeweek.gameplay-ingredients@5b823b4dbb/Editor/GameViewLink/LinkGameView.cs:58)
GameplayIngredients.Editor.LinkGameView.OnPlayModeChanged (UnityEditor.PlayModeStateChange state) (at Library/PackageCache/net.peeweek.gameplay-ingredients@5b823b4dbb/Editor/GameViewLink/LinkGameView.cs:104)
UnityEditor.EditorApplication.Internal_PlayModeStateChanged (UnityEditor.PlayModeStateChange state) (at <dc14d30a5e0540ee9311ed6df63d9074>:0)
`

Pressing play or stop.  Unity 2020 LTS

![image](https://user-images.githubusercontent.com/915232/129905288-a70c9b6d-ea55-4a08-b7b0-34f883d1dc78.png)

**Comment by twobob** [comment]
It's non-blocking but kinda annoying

**Comment by peeweek** [comment]
Sorry, I totally missed this one. I remember having this error thrown with LinkGameView active for a while, but it doesn't seem to be the case anymore. I tried with latest Cinemachine 2.9.2 and I can't seem to repro it. Seems that it fixed itself with a cinemachine update.
