### ISSUE TITLE
Editor Discover Window Content Sizing

### ISSUE THREAD

**Issue by Adjuvant** [peeweek/net.peeweek.gameplay-ingredients#62]
Unity Version: 2019.4
GPI Version: 2019.3.7

File: DiscoverWindow.cs
Line: [455](https://github.com/peeweek/net.peeweek.gameplay-ingredients/blob/b8a3f17bb4c5135e60e0af50d4f6d81ec57ee638/Editor/Discover/DiscoverWindow.cs#L455)

The Discovery content pane (not levels) has a Vertical Scope that uses a fixed width of 440 pixels, this squeezes all content into small space. 

I hacked it with this: 
`using (new GUILayout.VerticalScope(GUILayout.Width(discoverAsset.WindowWidth-discoverAsset.DiscoverListWidth-25)))`

Great work btw, this package is a dream to use for my instructional work!

**Comment by peeweek** [comment]
Thanks for pointing that out! :)
