### ISSUE TITLE
Unity 2022.1a12

### ISSUE THREAD

**Issue by XeonG** [peeweek/net.peeweek.gameplay-ingredients#63]
Just 2 minor errors with "Overlay GameplayIngredients.Editor.SceneViewToolbar+IngredientsCustomToolbarOverlay attempting to set unsupported layout: HorizontalToolbar
UnityEditor.WindowLayout:LoadDefaultWindowPreferences ()"

**Comment by peeweek** [comment]
I've got the error as well on 2021.3... sadly I can't figure out a proper solution right now :( Unless configure this overlay not to be a toolbar
