### ISSUE TITLE
upgrade library to 2.1.1

### ISSUE THREAD

**Issue by peppemas** [peeweek/net.peeweek.gameplay-ingredients#64]
With version 2.0.8 the HDRP Project does not work.

https://github.com/peeweek/net.peeweek.gameplay-ingredients/blob/b8a3f17bb4c5135e60e0af50d4f6d81ec57ee638/package.json#L11

**Comment by peeweek** [comment]
Sorry I didnt see this issue, I already upgraded the requirement to naughtyattributes 2.1.4, should fix your issue.
