### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by TheDirigible** [peeweek/net.peeweek.gameplay-ingredients#69]
I followed the instructions, but got this error:
[Package Manager Window] Cannot perform upm operation: Unable to add package [net.peeweek.gameplay-ingredients@2020.2.10]:
  Package net.peeweek.gameplay-ingredients@2020.2.10 has invalid dependencies or related test packages:
    com.dbrizov.naughtyattributes (dependency): Package [com.dbrizov.naughtyattributes@2.0.8] cannot be found [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

But Naughty Attributes 2.1.1 is already installed from the regular asset store.

**Comment by peeweek** [comment]
Ugh, this is a tough one :/ I think the package manager is looking for the non-asset store one, even though you already have it installed :( 

I'll get into the package description documentation but AFAIK there is no way to define a dependency to an asset store package.
