### ISSUE TITLE
Non-Unicode character in SelectionHistoryWindow.cs

### ISSUE THREAD

**Issue by SineNomine2001** [peeweek/net.peeweek.gameplay-ingredients#76]
Line 69 of [Editor](https://github.com/peeweek/net.peeweek.gameplay-ingredients/tree/master/Editor)/[SelectionHistory](https://github.com/peeweek/net.peeweek.gameplay-ingredients/tree/master/Editor/SelectionHistory)/SelectionHistoryWindow.cs:
```
if (GUILayout.Button("×", GUILayout.Width(16)))
```
Contains a non-Unicode character which breaks the code if your `Language for non-Unicode programs` setting is e.g. Chinese.

**Comment by peeweek** [comment]
You are right, thanks for pointing that out. Should be fixed in next release (2021.3.2)
